//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFRNavSim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VFRNavSim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;kml xmlns=&quot;http://www.opengis.net/kml/2.2&quot;
        ///  xmlns:gx=&quot;http://www.google.com/kml/ext/2.2&quot;&gt;
        ///&lt;Document&gt;
        ///  &lt;name&gt;VFR Nav Sim&lt;/name&gt;
        ///  &lt;open&gt;1&lt;/open&gt;
        ///  &lt;gx:Tour&gt;
        ///    &lt;name&gt;Current Aircraft Position&lt;/name&gt;
        ///    &lt;gx:Playlist&gt;
        ///      &lt;gx:FlyTo&gt;
        ///        &lt;gx:duration&gt;3.0&lt;/gx:duration&gt;
        ///        &lt;Camera&gt;
        ///          &lt;longitude&gt;%cLng%&lt;/longitude&gt;
        ///          &lt;latitude&gt;%cLat%&lt;/latitude&gt;
        ///          &lt;altitude&gt;%alt%&lt;/altitude&gt;
        ///          &lt;heading&gt;%hdg%&lt;/heading&gt;
        ///          &lt;til [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _currentEyePointAndIdentPointCam {
            get {
                return ResourceManager.GetString("_currentEyePointAndIdentPointCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;kml xmlns=&quot;http://www.opengis.net/kml/2.2&quot;
        ///  xmlns:gx=&quot;http://www.google.com/kml/ext/2.2&quot;&gt;
        ///
        ///&lt;Document&gt;
        ///  &lt;name&gt;VFR Nav Sim&lt;/name&gt;
        ///  &lt;open&gt;1&lt;/open&gt;
        ///
        ///  &lt;gx:Tour&gt;
        ///    &lt;name&gt;Current Aircraft Position&lt;/name&gt;
        ///    &lt;gx:Playlist&gt;
        ///      &lt;gx:FlyTo&gt;
        ///        &lt;gx:duration&gt;3.0&lt;/gx:duration&gt;
        ///        &lt;Camera&gt;
        ///          &lt;longitude&gt;%lng%&lt;/longitude&gt;
        ///          &lt;latitude&gt;%lat%&lt;/latitude&gt;
        ///          &lt;altitude&gt;%alt%&lt;/altitude&gt;
        ///          &lt;heading&gt;%hdg%&lt;/heading&gt;
        ///          &lt;tilt&gt;90&lt;/tilt&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _currentEyePointCam {
            get {
                return ResourceManager.GetString("_currentEyePointCam", resourceCulture);
            }
        }
    }
}
